### ISSUE TITLE
not able to access groups from ansible host playbook failed

### ISSUE THREAD

**Issue by thatsk** [ilias-sp/ansible-setup-passwordless-ssh#5]
fatal: [localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_host'

**Comment by thatsk** [comment]
not sure why this task is failing
```YAMlL
    - name: distribute the ssh key to the remote hosts
      shell: "/usr/local/bin/sshpass -p \"{{remote_machine_password}}\" ssh-copy-id -o StrictHostKeyChecking=no -i ~/.ssh/{{ssh_key_filename}}.pub  \"{{remote_machine_username}}@{{ hostvars[item].ansible_host }}\""
      register: ssh_copy_id_execution
      with_items:
        - "{{ groups['ansible_setup_passwordless_setup_group']}}"
      failed_when: ssh_copy_id_execution.rc != 0
```
