### ISSUE TITLE
how to access host variable if some output need to be copied to another host

### ISSUE THREAD

**Issue by thatsk** [ilias-sp/ansible-setup-passwordless-ssh#6]
```YAML ---
- name: Updating Rpm versions in {{ service_name }}
  hosts: local
  connection: local
  gather_facts: false
  tasks:
    - name: Getting host list from ipa
      shell: /etc/ansible/playbooks/hostfind.sh
    - name: Creating in memory inventory group for {{ nodetype }} in ansible playbook itself
      shell: cat /etc/ansible/hosts | grep {{ nodetype }} | grep {{ env }}
      register: host_list
    - add_host:
        name: "{{ item }}"
        group: "{{ nodetype }}"
      with_items: "{{ host_list.stdout_lines }}"

- name: Deployment Execution start on {{ nodetype }}
  hosts: "{{ nodetype }}"
  connection: ssh
  gather_facts: false
  any_errors_fatal: false
  user: test
  become: yes
  serial: 1
  tasks:
    - name: Deploying service on {{ inventory_hostname }}
      block:
        - name: Downgrading {{ service_name }} service on {{ inventory_hostname }}
          shell: rpm --queryformat "%{VERSION}-%{RELEASE}" -q {{ service_name }}
          register: downgraderpmversion
        - name: Restarting {{ service_name }} service on {{ inventory_hostname }}
          include_tasks: /etc/ansible/inventories/playbooks/common/service_restart.yaml
          with_items:
            - { servicename: '{{ service_name }}' }

- name: Updating Rpm versions for {{ service_name }}
  hosts: local
  connection: local
  gather_facts: false
  tasks:
    - debug:
        var: hostvars[groups['{{ nodetype }}'][0]]['downgraderpmversion']['stdout']
    - shell: echo "{hostvars[groups['{{ nodetype }}'][0]]['downgraderpmversion']['stdout']}"
 ```
